mi_bool = 4 < 5 < 6
mi_bool1 = 4 < 5 and 5 > 6
mi_bool2 = (4 < 5) and (5 == 2+3)
mi_bool3 = (55 == 55) and ('perro' == 'perro')
mi_bool4 = (10 == 10) or (3 == 3)
mi_bool5 = (1 == 10) or (3 == 3)
mi_bool6 = (1 == 10) or (3 == 10)
texto = "esta frase el breve"
mi_bool7 = ('frase' in texto) and ('breve' in texto)
mi_bool8 = ('frase' in texto) and ('python' in texto)
mi_bool9 = ('frase' in texto) or ('python' in texto)
mi_bool10 = not ('a' == 'a')
mi_bool11 = not ('a' == 'b')
mi_bool12 = not ('a' != 'a')
mi_bool13 = not ('a' != 'b')
print(mi_bool)
print(mi_bool1)
print(mi_bool2)
print(mi_bool3)
print(mi_bool4)
print(mi_bool5)
print(mi_bool6)
print(mi_bool7)
print(mi_bool8)
print(mi_bool9)
print(mi_bool10)
print(mi_bool11)
print(mi_bool12)
print(mi_bool13)